# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:17:40+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    AlsfcCertificatePostRequest,
    AlsfcCertificatePostResponse,
    AlsfcCertificatePostResponse1,
    AlsfcCertificatePostResponse2,
    AlsfcCertificatePostResponse3,
    AlsfcCertificatePostResponse4,
    AlsfcCertificatePostResponse5,
    AlsfcCertificatePostResponse6,
    ClcerCertificatePostRequest,
    ClcerCertificatePostResponse,
    ClcerCertificatePostResponse1,
    ClcerCertificatePostResponse2,
    ClcerCertificatePostResponse3,
    ClcerCertificatePostResponse4,
    ClcerCertificatePostResponse5,
    ClcerCertificatePostResponse6,
    SrcerCertificatePostRequest,
    SrcerCertificatePostResponse,
    SrcerCertificatePostResponse1,
    SrcerCertificatePostResponse2,
    SrcerCertificatePostResponse3,
    SrcerCertificatePostResponse4,
    SrcerCertificatePostResponse5,
    SrcerCertificatePostResponse6,
)

app = MCPProxy(
    description='APIs provided by Department of Labour, Govt of Punjab, Punjab.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Department of Labour, Govt of Punjab, Punjab',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/pblabour/v3'}],
)


@app.post(
    '/alsfc/certificate',
    description=""" API to verify Application/ License for Factory. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def alsfc(body: AlsfcCertificatePostRequest = None):
    """
    Application/ License for Factory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/clcer/certificate',
    description=""" API to verify Registration Certificate for Contract Labour License. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def clcer(body: ClcerCertificatePostRequest = None):
    """
    Registration Certificate for Contract Labour License
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/srcer/certificate',
    description=""" API to verify Registration Certificate of Shops And Commercial Establishment. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def srcer(body: SrcerCertificatePostRequest = None):
    """
    Registration Certificate of Shops And Commercial Establishment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
